### PR TITLE
feat: adding new feature to optimize apps

### PR DESCRIPTION
**Pull request by onedionys**
- Adding new yaml

### CODE REVIEW

**Comment by aredridel** [comment]
Hello! Can you please tell me a bit of background on these changes?

**Comment by onedionys** [comment]
> Hello! Can you please tell me a bit of background on these changes?

Hello, I added that code to speed up the use of node-bin-gen. I realized it when using node-bin-gen because it takes a while.
You can approve the PR or not, feel free. However, I recommend approving it so that it can be useful for others who use node-bin-gen. Thanks for your feedback!

**Comment by aredridel** [comment]
And how does it speed it up?

**Comment by aredridel** [comment]
I believe this PR is LLM-generated spam trying to integrate the pkgx project.

**Comment by onedionys** [comment]
> I believe this PR is LLM-generated spam trying to integrate the pkgx project.

Yep, you're right. Actually, I only want to add one file, tea.yml, to your repository. Because I have a job that requires uploading the file and I also don't know what it is used for.
I apologize and thank you 😓🙏

**Comment by oldherl** [comment]
This is a crypto scam and the PR author is trying to steal potential tokens from you.
https://connortumbleson.com/2024/02/26/the-disappointing-tea-xyz/

**Comment by aredridel** [comment]
So this is not something I ever want to see here: this is trying to collect payment for the use of the module on behalf of someone else, and promoting the 'tea' and 'pkgx' systems that appear to be throwing as much LLM as they can at the thing. 

There's more discussion [here](https://kolektiva.social/@aredridel/111998475796358898), and it's welcome on this thread if you're not on Mastodon. 

At the moment my stance is that 'tea is considered harmful'. Given the LLM-generated descriptions on pkgx, and the stable diffusion-ish images there, I'm inclined to think the same about that project.

**Comment by xvello** [comment]
@mxcl @ryanml @michaelessiet this is obvious proof that the person behind the '0x9BAac40A197bbb110ae5B2f31342D8d15D734832' wallet is paying people to steal other project's ownership. What will you do to punish that person and all the others who are running the same scam and wasting maintainer time?

**Comment by mxcl** [comment]
Hey, we will be punishing this user, probably with a full ban and tracing as much as possible all activity they may have with other accounts and banning those too. If I could I would also ban all their friends and family too. This behavior is disgusting and counter productive to our mission. I am furious about it.

Additionally we are taking steps to force users to prove they can commit before allowing them to generate the YAML which should prevent idiots like @onedionys from being able to figure out how to create the file.

**Comment by onedionys** [comment]
> Hey, we will be punishing this user, probably with a full ban and tracing as much as possible all activity they may have with other accounts and banning those too. If I could I would also ban all their friends and family too. This behavior is disgusting and counter productive to our mission. I am furious about it.
> 
> Additionally we are taking steps to force users to prove they can commit before allowing them to generate the YAML which should prevent idiots like @onedionys from being able to figure out how to create the file.
> 
> tea aims to change the nature of open source sustainability. Our mission is pure and we want to help projects like yours to flourish.
> 
> pkgx was using LLMs to generate some images and descriptions but we have removed them due to concern from the community. Nothing else is using AI or LLMs in pkgx or tea.

I'm sorry, I just joined the crypto/airdrop community not even a week ago. And for what I did, I just followed someone doing the same thing and it worked, so I followed that method by doing PR to someone's repo.

I didn't know that it wasn't allowed, because in the article I read, I had to contribute to someone's repo and add tea.yml OR add it to my own repo. I admit my mistake and will not make this mistake again and make it a lesson for the future, sir.

I apologize @aredridel for trying to do a Pull Request and wasting your precious time.

**Comment by xvello** [comment]
> which should prevent idiots like @onedionys from being able to figure out how to create the file.

Wow, slow down @mxcl. Calling people names is not constructive not warranted here. If someone were to deserve such an adjective, it would be the person who designs a system that financially incentivizes malicious actors without implementing proper guardrails against such actors. And no, shifting the moderation burden to unpaid Open-Source maintainers is not a proper guardrail.

**Comment by mxcl** [comment]
I apologize @onedionys and @xvello, there is no call for my behavior.

Our guardrail will be making it so onboarding a project requires a check against that project via the GitHub API, it should prevent these types of pull requests and reduce the burden to zero on open source maintainers.

Our goal is to make open source sustainable and we failed here, but it will be fixed by end of day.

**Comment by aredridel** [comment]
I have some really deep doubts that's true: the incentives you're creating here are pretty obviously easy to abuse.

**Comment by rugk** [comment]
Maybe we should write a bot that finds these PRs on GitHub and uses an LLM to comment on all the PRs to mark them as spam and additionally reports the user accounts to GitHub? 🙃

**Comment by xvello** [comment]
@mxcl the PR spam is continuing, see [github search](https://github.com/search?q=tea.xyz%2Fwhat-is-this-file&type=pullrequests&s=created&o=desc): 
image

**Comment by stuaxo** [comment]
> Maybe we should write a bot that finds these PRs on GitHub and uses an LLM to comment on all the PRs to mark them as spam and additionally reports the user accounts to GitHub? 🙃

I'm not sure you even need an LLM if all the comments are the same.

**Pull request closed without merging**
